name: Terraform Configuration Aliases
description: Generate aliased provider blocks that satisfy required configuration aliases
inputs:
  path:
    description: The path to the Terraform module
    required: false
    default: ''
runs:
  using: composite
  steps:
    - run: go get github.com/hashicorp/terraform-config-inspect
      shell: bash
      env:
        GO111MODULE: 'on'
    - run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      shell: bash
    - run: cd "${{ inputs.path }}" && ${{ github.action_path }}/providers.sh | tee aliased-providers.tf.json
      shell: bash
